# Generated by Django 4.0.2 on 2022-02-16 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_article_published'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'ordering': ['-id'], 'verbose_name': 'Контент', 'verbose_name_plural': 'Контент'},
        ),
    ]
