# Generated by Django 4.0.2 on 2022-02-16 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0010_alter_content_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="content",
            options={
                "ordering": ["id"],
                "verbose_name": "Контент",
                "verbose_name_plural": "Контент",
            },
        ),
    ]
