from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('articles/create/',
         views.ArticleCreateView.as_view(),
         name='article_create'),
    path('articles/edit/header/<int:article_id>/',
         views.ArticleUpdateView.as_view(),
         name='article_header_edit'),
    path('articles/delete/<int:article_id>/',
         views.ArticleDeleteView.as_view(),
         name='article_delete'),
    path('articles/edit/<int:article_id>/<str:model_name>/create/',
         views.ContentCreateUpdateView.as_view(),
         name='content_create'),
    path('articles/edit/<int:article_id>/<str:model_name>/update/<int:content_object_id>/',
         views.ContentCreateUpdateView.as_view(),
         name='content_update'),
    path('articles/edit/<int:article_id>/delete/<int:content_id>/',
         views.ContentDeleteView.as_view(),
         name='content_delete'),
    path('articles/edit/<int:article_id>/',
         views.ArticlePreviewEditView.as_view(),
         name='article_edit'),
    path('articles/edit/<int:article_id>/publish/',
         views.publish_article_view,
         name='article_publish'),
    path('articles/',
         views.ArticleListView.as_view(),
         name='article_list'),
    path('articles/<slug:category_slug>/',
         views.ArticleListView.as_view(),
         name='article_list_by_category'),
    path('<str:username>/articles/',
         views.UserArticleListView.as_view(),
         name='users_article_list'),
    path('<str:username>/articles/<slug:category_slug>/',
         views.UserArticleListView.as_view(),
         name='users_article_list_by_category'),
    path('articles/detail/<int:article_id>/',
         views.ArticleDetailView.as_view(),
         name='article_detail'),
    path('like/',
         views.ArticleLikeView.as_view(),
         name='article_like')
]
